import argparse
import json
import re
from pathlib import Path

from settings_scripts import parse_and_sort_json_file, update_header_file, update_scopes, update_src_code
from settings_scripts.config import (
    DUCKDB_AUTOGENERATED_SETTINGS_FILE,
    DUCKDB_SETTINGS_HEADER_FILE,
    DUCKDB_SETTINGS_SCOPE_FILE,
    JSON_PATH,
    SettingsList,
    make_format,
)
from settings_scripts.update_autogenerated_functions import add_autogenerated_functions
from settings_scripts.update_settings_header_file import generate_content
from settings_scripts.update_settings_scopes import generate_scope_code

CPP_TOKEN = re.compile(
    r'"(?:\\.|[^"\\])*"'
    r"|'(?:\\.|[^'\\])*'"
    r"|[A-Za-z_]\w*"
    r"|(?:\d+\.\d*|\d+)"
    r"|::|->|==|!=|<=|>=|&&|\|\||<<|>>"
    r"|\S"
)


def normalized_cpp(source: str) -> tuple[str, ...]:
    """Tokenize generated C++ while treating adjacent string literals as one."""
    result: list[str] = []
    for token in CPP_TOKEN.findall(source):
        if token.startswith('"') and result and result[-1].startswith('"'):
            result[-1] = result[-1][:-1] + token[1:]
        else:
            result.append(token)
    return tuple(result)


def generated_source_drift() -> list[str]:
    checks = (
        (Path(DUCKDB_SETTINGS_HEADER_FILE), generate_content(DUCKDB_SETTINGS_HEADER_FILE)),
        (Path(DUCKDB_SETTINGS_SCOPE_FILE), generate_scope_code(DUCKDB_SETTINGS_SCOPE_FILE)),
        (
            Path(DUCKDB_AUTOGENERATED_SETTINGS_FILE),
            add_autogenerated_functions(DUCKDB_AUTOGENERATED_SETTINGS_FILE)[0],
        ),
    )
    drift = []
    for path, expected in checks:
        if normalized_cpp(path.read_text(encoding="utf-8")) != normalized_cpp(expected):
            drift.append(str(path))
    with Path(JSON_PATH).open(encoding="utf-8") as source:
        settings = json.load(source)
    if settings != sorted(settings, key=lambda setting: setting["name"]):
        drift.append(str(JSON_PATH))
    return drift


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate DuckDB settings sources")
    parser.add_argument("--check", action="store_true", help="fail if checked-in settings sources are stale")
    return parser.parse_args(argv)


if __name__ == '__main__':
    args = parse_args()
    parse_and_sort_json_file(write_sorted=not args.check)
    if args.check:
        drift = generated_source_drift()
        if drift:
            raise SystemExit("stale generated settings sources: " + ", ".join(drift))
        print(f"- Verified {len(SettingsList)} generated setting(s)")
        raise SystemExit(0)
    update_header_file()
    update_scopes()
    update_src_code()
    make_format()
    print(f"- Successfully parsed and included {len(SettingsList)} setting(s)!")
